name: Continuous Integration / Continuous Deployment

concurrency:
  group: deploy-${{ github.repository }}
  cancel-in-progress: false

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  ORG: ${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.event.repository.name }}
  CONT_NAME: ${{ github.event.repository.name }}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: ci
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Run tests
      run: ./gradlew test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: ci
    steps:
      - uses: actions/checkout@v4

      - name: Set organization name to lowercase
        run: |
          echo "ORG_LC=${ORG,,}" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Get current date
        id: getDate
        run: echo "date=$(date +%Y%m%d%H%M%S)" >> "$GITHUB_OUTPUT"

      - name: Cache Gradle files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin
        
      - name: Build and push image
        run: |
          docker build \
            -t $REGISTRY/$ORG_LC/$IMAGE_NAME:latest \
            -t $REGISTRY/$ORG_LC/$IMAGE_NAME:${{ steps.getDate.outputs.date }} \
            .
          docker push $REGISTRY/$ORG_LC/$IMAGE_NAME --all-tags

  deploy:
    needs: build-and-push
    runs-on: [ 'self-hosted', 'backend' ]
    env:
      TZ: Asia/Seoul
    steps:
      - name: Set organization name to lowercase
        run: |
          echo "ORG_LC=${ORG,,}" >> $GITHUB_ENV
          
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin
          
      - name: Getting current image name
        id: current_img
        run: |
          CURRENT_IMG=$(docker inspect $CONT_NAME --format='{{.Config.Image}}' 2>/dev/null || echo "")
          echo "image=$CURRENT_IMG" >> $GITHUB_OUTPUT

      - name: Pulling latest image
        run: docker pull $REGISTRY/$ORG_LC/$IMAGE_NAME:latest

      - name: Executing container using Docker Compose
        run: |
          docker compose \
          -f ${{ secrets.FESTIVAL_DOCKER_COMPOSE_FILE_PATH }} \
          --env-file ${{ secrets.FESTIVAL_ENV_PATH }} \
          up -d --no-build --pull never \
          $CONT_NAME

      - name: Flushing docker cache
        run: docker buildx prune -f
